"""Safety helpers for identifying PaperFlow-generated files."""

from __future__ import annotations

from collections.abc import Iterable
from pathlib import Path

GENERATED_FILE_MARKER = """<!--
AUTO-GENERATED BY PAPERFLOW.
DO NOT EDIT MANUALLY.
SOURCE: configs/topics.yaml + data/papers.json
-->
"""


def is_generated_file(path: Path) -> bool:
    """Return whether *path* starts with the exact PaperFlow marker.

    Files that cannot be read as UTF-8 are treated as manual files. This function is
    intentionally conservative because its result can later authorize stale cleanup.
    """
    if not path.is_file():
        return False
    try:
        return path.read_text(encoding="utf-8").startswith(GENERATED_FILE_MARKER)
    except (OSError, UnicodeError):
        return False


def generated_cleanup_candidates(paths: Iterable[Path]) -> tuple[Path, ...]:
    """Return only marker-confirmed paths, in deterministic order."""
    return tuple(sorted((path for path in paths if is_generated_file(path)), key=str))
